# Generated by Django 4.2.25 on 2025-11-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_account_username_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='place_of_work',
            new_name='work',
        ),
    ]
