# Generated by Django 4.2.24 on 2025-09-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_admin_list_universityadmin_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='university_admin',
        ),
        migrations.RemoveField(
            model_name='universityadmin',
            name='admin',
        ),
        migrations.AddField(
            model_name='universityadmin',
            name='student_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.universityadmin'),
        ),
    ]
