# Generated by Django 4.2.25 on 2025-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology',
            name='pathology_images',
            field=models.ImageField(default=1, upload_to='static/pathologies_img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_description',
            field=models.TextField(blank=True),
        ),
    ]
