# Generated by Django 4.2.25 on 2025-12-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_place_of_work_workerprofile_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_img',
            field=models.ImageField(upload_to='case_layers/'),
        ),
        migrations.AlterField(
            model_name='pathologyimage',
            name='image',
            field=models.ImageField(upload_to='pathology_img/'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_description_img',
            field=models.ImageField(upload_to='schemes/scheme_description_img/'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_img',
            field=models.ImageField(upload_to='schemes/scheme_img/'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='grade',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
